### ISSUE TITLE
IP ban check whitelist

### ISSUE THREAD

**Issue by DeWilX** [ruany/LiteBans#19] opened 2017-08-16 15:17 UTC
Hello, I really need this command (ASAP, because I really like your plugin and I would like to switch from MaxBans):

> /mbwhitelist <name or UUID> - Allows the given user to bypass IP bans (Not regular bans! Eg, use for players with siblings who need to be IP banned)
> 
> /MaxBans/
> 

which stores playernames in database [http://prntscr.com/g98lgi](url) (MySQL, etc.) and check for match.

Thanks.

**Comment by ruany** [comment] 2017-08-16 15:21
Duplicate of #18

**Closed by ruany** 2017-08-16 15:21 UTC
